name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: make build
    - name: Run unit tests
      run: make test
    - name: Run vet
      run: make vet
  lint:
    env:
      GOLANGCI_LINT_V: 1.26.0
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Install golangci-lint
      run: >
        cd /tmp &&
        mkdir -p $(go env GOPATH)/bin &&
        wget -q https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_V}/golangci-lint-${GOLANGCI_LINT_V}-linux-amd64.tar.gz &&
        tar xf golangci-lint-${GOLANGCI_LINT_V}-linux-amd64.tar.gz &&
        mv golangci-lint-${GOLANGCI_LINT_V}-linux-amd64/golangci-lint $(go env GOPATH)/bin &&
        rm -fr golangci-lint-*
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run golangci-lint
      run: make lint
